// REGISTRY. The style count can never go stale because nobody counts styles by hand: every new
// plate exports `STYLE` and describes itself, the eleven that predate the export are declared in
// styles.legacy.json, and this writes the merged, sorted truth to styles.gen.json and
// references/styles/INDEX.md. docs-check.mjs and gallery.mjs read the same registry, so prose,
// pictures and code cannot drift apart.
//   node tools/registry.mjs
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const ENGINE = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const ROOT = resolve(ENGINE, "..");
const CORE = join(ENGINE, "src/canvas-core");

// A plate declares itself with one flat literal, `export const STYLE = { id, name, family,
// medium, nearest, hero }`. A regex on the literal is enough — it has no nested braces — and it
// means a plate that does not even bundle yet still shows up in the count instead of silently
// going missing. A literal that will not evaluate is reported, not skipped.
export const loadRegistry = () => {
  const scanned = readdirSync(CORE).filter((f) => f.endsWith(".ts")).map((f) => {
    const m = readFileSync(join(CORE, f), "utf8").match(/export\s+const\s+STYLE\s*=\s*(\{[\s\S]*?\})\s*;/);
    if (!m) return null;
    let style; try { style = new Function(`return (${m[1]})`)(); } catch (e) { throw new Error(`unparseable STYLE in src/canvas-core/${f}: ${e.message}`); }
    for (const k of ["id", "name", "family", "medium", "nearest", "hero"]) if (typeof style[k] !== "string") throw new Error(`src/canvas-core/${f}: STYLE.${k} missing or not a string`);
    return { ...style, source: "scanned" };
  }).filter(Boolean);

  const legacy = JSON.parse(readFileSync(join(ENGINE, "styles.legacy.json"), "utf8")).styles.map((s) => ({ ...s, source: "legacy" }));

  const byId = new Map(), shadowed = [];
  for (const s of legacy) byId.set(s.id, s);
  // A house style (a hand matched from someone's image) or a recreation/study USES a hand; it is not a new one.
  scanned.splice(0, scanned.length, ...scanned.filter((s) => !s.house && !s.recreationOf && !s.study));
  // "<plate>Draw" is the drawing film of an existing hand, not a new hand: fold it into its parent.
  const drawOf = (s) => (s.id.endsWith("Draw") && byId.has(s.id.slice(0, -4)) ? s.id.slice(0, -4) : null);
  for (const s of scanned.filter(drawOf)) byId.set(drawOf(s), { ...byId.get(drawOf(s)), drawFilm: s.id });
  for (const s of scanned.filter((x) => !drawOf(x))) { if (byId.has(s.id)) shadowed.push(s.id); byId.set(s.id, s); } // the plate's own word replaces legacy's memory of it, whole record, `film` and all

  const styles = [...byId.values()].map(enrich).sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  styles.shadowed = shadowed;
  return styles;
};

const enrich = (s) => {
  // The draw film is the drawing process itself: a <id>Draw.ts plate beats the plain plate, and
  // an explicit `film: null` (a hand that only lives inside a bigger film) is honoured.
  let drawFilm = null;
  const plate = join(CORE, `${s.id}.ts`), host = join(ENGINE, "src/hosts", `page-${s.id}.ts`);
  if (existsSync(join(CORE, `${s.id}Draw.ts`))) drawFilm = `${s.id}Draw`;
  else if (typeof s.film === "string") drawFilm = s.film;
  else if (s.film === null) drawFilm = null;
  else if (existsSync(plate) && existsSync(host) && new RegExp(`export const ${s.id}\\s*:\\s*Film`).test(readFileSync(plate, "utf8"))) drawFilm = s.id;
  const module = existsSync(plate) ? `engine/src/canvas-core/${s.id}.ts` : s.module ?? null;
  return { id: s.id, name: s.name, family: s.family, medium: s.medium, nearest: s.nearest, hero: s.hero, module, drawFilm, samples: `anidoodle-research/samples/${s.id}/`, source: s.source };
};

const writeOutputs = (styles) => {
  const gen = styles.map((s) => ({ id: s.id, name: s.name, family: s.family, medium: s.medium, nearest: s.nearest, hero: s.hero, module: s.module, drawFilm: s.drawFilm, samples: s.samples, source: s.source }));
  writeFileSync(join(ENGINE, "styles.gen.json"), JSON.stringify(gen, null, 2) + "\n");
  const dir = join(ROOT, "references/styles");
  const rows = styles.map((s, i) => `| ${i + 1} | ${s.name} (\`${s.id}\`) | ${s.medium} | ${s.module ? `\`${s.module}\`` : "—"} | ${s.drawFilm ? `\`engine/src/canvas-core/${s.drawFilm}.ts\`` : "—"} | \`${s.samples}\` |`);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "INDEX.md"), [
    "# Style index", "",
    "Generated by `node tools/registry.mjs` (run from `engine/`) out of `export const STYLE`",
    "blocks in `engine/src/canvas-core/` plus `engine/styles.legacy.json`. Do not edit by hand.", "",
    "| # | style | medium | hero module | draw-film module | samples |",
    "|---|---|---|---|---|---|",
    ...rows, "",
    `${styles.length} styles.`, "",
  ].join("\n"));
};

if (import.meta.url === `file://${process.argv[1]}`) {
  const styles = loadRegistry();
  writeOutputs(styles);
  for (const s of styles) console.log(`  ${s.id.padEnd(14)} ${s.name.padEnd(32)} ${s.drawFilm ? "film " + s.drawFilm : "no film   "}${s.source === "scanned" ? "" : "  (legacy)"}`);
  if (styles.shadowed.length) console.log(`  note: scanned STYLE replaced legacy record for ${styles.shadowed.join(", ")}`);
  console.log(`\n${styles.length} styles -> engine/styles.gen.json + references/styles/INDEX.md`);
}
