// SNAP. Proof stills for scene work: render N sample frames of one shot (or of every shot) on
// ONE uncontended page, and optionally tile them into a contact sheet a human can look at.
//   node tools/snap.mjs <film> [--shot id] [--samples N] [--sheet] [--only] [--scale S] [--out path]
// --only bundles the film with every SIBLING shot module shimmed to a no-op, so parallel scene
// work is never blocked by a sibling file that does not compile. Needs --shot in that mode.
import { build } from "esbuild";
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { buildPage } from "./build-page.mjs";
import { detect } from "./detect.mjs";
import * as playwright from "./adapters/playwright.mjs";

const VAL = new Set(["shot", "samples", "scale", "out"]);
const pos = [], opt = {};
for (let i = 2; i < process.argv.length; i++) { const a = process.argv[i]; if (a.startsWith("--")) opt[a.slice(2)] = VAL.has(a.slice(2)) ? process.argv[++i] : true; else pos.push(a); }
const [film] = pos, shotId = opt.shot, samples = Math.max(1, +(opt.samples ?? 6)), scale = +(opt.scale ?? 1);
const die = (m) => { console.error(`snap: ${m}`); process.exit(1); };
if (!film) die("usage: node tools/snap.mjs <film> [--shot id] [--samples N] [--sheet] [--only] [--scale S] [--out path]");
if (opt.only && !shotId) die("--only needs --shot <id>: the one shot to bundle for real");
if (!existsSync(`src/canvas-core/${film}.ts`)) die(`no film module at src/canvas-core/${film}.ts`);
if (opt.only && !existsSync(`src/canvas-core/${film}/${shotId}.ts`)) die(`--only: no shot module at src/canvas-core/${film}/${shotId}.ts`);

// --only: shim every relative import from the film module that lands in its shot dir, except the target
const onlyPlugin = opt.only ? (() => {
  const target = resolve(`src/canvas-core/${film}/${shotId}.ts`).replace(/\.ts$/, ""), shims = {};
  let n = 0;
  for (const [, bindings, spec] of readFileSync(`src/canvas-core/${film}.ts`, "utf8").matchAll(/import\s*\{([^}]+)\}\s*from\s*"(\.[^"]+)"/g)) {
    const abs = resolve("src/canvas-core", spec).replace(/\.ts$/, "");
    if (!abs.startsWith(resolve(`src/canvas-core/${film}/`)) || abs === target) continue;
    const names = bindings.split(",").map((b) => b.trim().split(/\s+as\s+/)[0]).filter(Boolean);
    const shim = resolve(`.tmp/snap/shim-${film}-${n++}.ts`);
    mkdirSync(dirname(shim), { recursive: true });
    writeFileSync(shim, `// GENERATED by tools/snap.mjs (--only shim)\n${names.map((nm) => `export const ${nm} = () => undefined;`).join("\n")}\n`);
    shims[abs] = shim;
  }
  if (!Object.keys(shims).length) console.error("snap: --only: no sibling modules found to shim (shots may be inline in the film module)");
  else console.log(`--only: siblings shimmed to no-ops: ${Object.keys(shims).map((p) => p.split("/").pop()).join(", ")}`);
  return [{ name: "snap-only", setup: (b) => b.onResolve({ filter: /^[.]/ }, (args) => { const hit = shims[resolve(dirname(args.importer), args.path).replace(/\.ts$/, "")]; return hit ? { path: hit } : null; }) }];
})() : [];

// the film's own shots and meta, read through the same shim in --only mode
const probe = (await build({ stdin: { contents: `export { ${film} as film } from "./src/canvas-core/${film}";`, resolveDir: process.cwd(), loader: "ts" }, bundle: true, format: "esm", write: false, platform: "neutral", plugins: onlyPlugin })).outputFiles[0].text;
const f = (await import("data:text/javascript;base64," + Buffer.from(probe).toString("base64"))).film;
const targets = shotId ? [f.shots.find((s) => s.id === shotId) ?? die(`film '${film}' has no shot '${shotId}' (has: ${f.shots.map((s) => s.id).join(", ")})`)] : f.shots;

const env = detect();
if (!env.chosen) die("no render backend found (snap draws real frames); the HTML player still works: node tools/build-page.mjs");
const entry = opt.only ? (mkdirSync(".tmp/snap", { recursive: true }), resolve(`.tmp/snap/page-${film}--${shotId}.ts`)) : `src/hosts/page-${film}.ts`;
if (opt.only) writeFileSync(entry, `// GENERATED by tools/snap.mjs (--only bundle)\nimport { ${film} } from "../../src/canvas-core/${film}";\nimport { mountFilm } from "../../src/hosts/page";\nmountFilm(${film});\n`);
const page = await buildPage({ entry, out: resolve(opt.only ? `dist/snap-${film}--${shotId}.html` : `dist/${film}.html`), title: film, plugins: onlyPlugin });
console.log(`page: ${page.out} (${(page.bytes / 1024).toFixed(0)} KB)`);
const session = await playwright.open(env, page.out, { scale, workers: 1 });

// N evenly spaced frames across [start, end), first and last included
const framesOf = (s) => { const n = Math.min(samples, s.end - s.start); return Array.from({ length: n }, (_, i) => s.start + Math.round((i * (s.end - s.start - 1)) / Math.max(1, n - 1))); };
console.log(`film: "${f.meta.title}" ${f.meta.W}x${f.meta.H}, ${samples} sample(s) per shot, scale ${scale}`);
for (const s of targets) {
  const dir = join(".tmp", "snap", film, s.id), fs = framesOf(s), ms = [];
  mkdirSync(dir, { recursive: true });
  let i = 0;
  for (const fr of fs) { const r = await session.frame(fr, 0); ms.push(r.drawMs); writeFileSync(join(dir, `f${String(i++).padStart(4, "0")}.png`), r.png); if (r.shot !== s.id) console.error(`snap: warning: frame ${fr} was drawn by shot '${r.shot}', expected '${s.id}'`); }
  console.log(`  ${s.id.padEnd(12)} frames ${fs.join(", ")}   draw ms [${ms.map((m) => m.toFixed(0)).join(", ")}]   -> ${dir}`);
  if (opt.sheet) {
    const cols = Math.ceil(Math.sqrt(fs.length)), rows = Math.ceil(fs.length / cols), out = targets.length === 1 && opt.out ? resolve(opt.out) : resolve(`out/snap-${film}-${s.id}.png`);
    mkdirSync(dirname(out), { recursive: true });
    execFileSync(env.ffmpeg.bin, ["-y", "-loglevel", "error", "-start_number", "0", "-framerate", "1", "-i", join(dir, "f%04d.png"), "-vf", `scale=360:-2,tile=${cols}x${rows}`, "-frames:v", "1", out]);
    console.log(`    sheet: ${out} (${cols}x${rows})`);
  }
}
await session.close();
